server:
  servlet:
    context-path: /environmentmonitoring
spring:
  profiles:
    active: dev
  # 出现404错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
  # AOP切面启用
  aop:
    proxy-target-class: true
    auto: true
# swagger2管理平台扫描接口路径
controller_path: com.upsoft.environmentmonitoring.controller

# AQI抓取配置
resttemplate:
  connection.timeout: 10000
  read.timeout: 10000
  url.sichuan_aqi: http://182.148.109.15:82/PublishService/air/cityAirReal.vm
  url.sichuan_aqi_city_code: 5109
  url.sichuan_city_hour_aqi_type: H
  url.sichuan_station_hour_aqi_type: SH
  url.sichuan_city_day_aqi_type: D
  url.sichuan_station_day_aqi_type: SD

# 视频融控平台配置
video_platform:
  url: http://172.16.5.95:7100/upapi
  username: ENC(VGugcU7rewrbArc/AIMfQA==)
  password: ENC(KZrUvGQNVuNgaCqvXSPkoqEfmLp5ciVqC/aQEUDPw+Ktzz1QBwEZ+mMagTSqevUS)

# mybatis-plus配置
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

# logback日志配置
log:
  # 输出位置
  home-dir: /opt/emLogs
  # 日志最大的历史天数
  maxHistory: 15
  # 输出级别
  level: debug
  # 单个log文件大小设置
  max-file-size: 10MB
  
# 配置jasypt加解密跟秘钥
jasypt:
  encryptor:
    password: environmentmonitoring
    
---
server:
  port: 8080
spring:
  profiles: dev
  # 数据源和数据池配置
  datasource:
    dynamic:
      primary: environmentmonitoring
      datasource:
        environmentmonitoring:
          # 数据源基本配置
          url: jdbc:mysql://172.16.254.3:3306/environmentmonitoring?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(PGvE1P/Xfiiby/4696KF/g==)
          password: ENC(FBikpARdeBdhEze0HB0B9g==)
        user:
          # 数据源基本配置
          url: jdbc:mysql://172.16.1.19:3306/bp_user_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(C+iYPwQecqgtKOpBoNkPYw==)
          password: ENC(Duqd5o12b+cuV3BoNqy7pw==)
        aqm:
          # 数据源基本配置
          url: jdbc:mysql://172.16.254.107:3306/aqm_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(go4OJvmNStR3mJ2Jhfa5mA==)
          password: ENC(offTRICJwY08MoAey9GsnQ==)
      druid:
        # 数据源其他配置
        initialSize: 2
        minIdle: 4
        maxActive: 20
        maxWait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        connection-properties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=500; config.decrypt=true
        filters: stat,wall,slf4j,config
        # Spring监控配置，说明请参考Druid Github Wiki，spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
        aop-patterns: com.upsoft.intelligenteye.service.*
        # WebStatFilter和StatViewServlet配置，说明请参考Druid Wiki
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        web-stat-filter:
          enabled: true
          url-pattern: /*
          # exclusions配置第一个不能以*开头否则报错
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
          session-stat-enable: false
          session-stat-max-count: 1000
        stat-view-servlet:
          enabled: true
          # 配置druid监控登陆地址、登陆账号和密码
          url-pattern: /druid/*
          login-username: ENC(zQV4Cauwtilk4J3P8K4dMQ==)
          login-password: ENC(jLw02IaXVb9QGNn/LLpCww==)
          reset-enable: true

---
server:
  port: 8080
spring:
  profiles: test
  # 数据源和数据池配置
  datasource:
    dynamic:
      primary: environmentmonitoring
      datasource:
        environmentmonitoring:
          # 数据源基本配置
          url: jdbc:mysql://172.16.1.170:3306/environmentmonitoring?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(5D+0esAzHQjqq1YgcQml3w==)
          password: ENC(UTA4yRdWJxG023svPttrbQ==)
        user:
          # 数据源基本配置
          url: jdbc:mysql://172.16.1.19:3306/bp_user_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(C+iYPwQecqgtKOpBoNkPYw==)
          password: ENC(Duqd5o12b+cuV3BoNqy7pw==)
        aqm:
          # 数据源基本配置
          url: jdbc:mysql://172.16.254.107:3306/aqm_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ENC(go4OJvmNStR3mJ2Jhfa5mA==)
          password: ENC(offTRICJwY08MoAey9GsnQ==)
      druid:
        # 数据源其他配置
        initialSize: 2
        minIdle: 4
        maxActive: 20
        maxWait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        connection-properties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=500; config.decrypt=true
        filters: stat,wall,slf4j,config
        # Spring监控配置，说明请参考Druid Github Wiki，spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
        aop-patterns: com.upsoft.intelligenteye.service.*
        # WebStatFilter和StatViewServlet配置，说明请参考Druid Wiki
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        web-stat-filter:
          enabled: true
          url-pattern: /*
          # exclusions配置第一个不能以*开头否则报错
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
          session-stat-enable: false
          session-stat-max-count: 1000
        stat-view-servlet:
          enabled: true
          # 配置druid监控登陆地址、登陆账号和密码
          url-pattern: /druid/*
          login-username: ENC(zQV4Cauwtilk4J3P8K4dMQ==)
          login-password: ENC(jLw02IaXVb9QGNn/LLpCww==)
          reset-enable: true

---
server:
  port: 8083
spring:
  profiles: prod