# 数据源基本配置
#url: jdbc:mysql://198.46.194.130:3306/intelligenteye?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
url: jdbc:mysql://172.16.254.3/environmentmonitoring?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
driver-name: com.mysql.cj.jdbc.Driver
username: root
password: upsoft
# 自动代码生成的默认输出文件夹
output-dir: /src/main/java
# 作者
author: Wang wanqian
# 设置父包名
parent-package: com.upsoft.environmentmonitoring
# 设置Entity包名
entity-package: domain.po
# 设置Mapper包名
dao-package: dao
# 设置service包名
service-package: service
# 设置service实现类包名
serviceImpl-package: service.impl
# 设置controller包名
controller: controller
# 设置需要自动生成代码的表名
tables: t_user
# 设置表前缀
table-prefix: t_
# 自定义模板文件夹路径
template-path: templates/